spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_attendance_system?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin

logging:
  level:
    root: info
    org:
      springframework: ERROR

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health,beans,mappings,env,configprops,scheduledtasks